### ISSUE TITLE
vrpathreg is not found sometimes

### ISSUE THREAD

**Issue by HimbeersaftLP** [KinectToVR/k2vr-installer-gui#11]
Either the SteamVR location detection algorithm doesn't work perfectly or SteamVR just forgets to include it sometimes. Might also be related to #10 

https://github.com/KinectToVR/k2vr-installer-gui/blob/88ade20a42515353336111385f1b33b9d177e04b/k2vr-installer-gui/Tools/InstallerState.cs#L166-L172

**Comment by hyblocker** [comment]
Should the installer manually update the JSON itself to workaround this? It seems to be a more reliable approach.

**Comment by HimbeersaftLP** [comment]
Ooop, Ella actually already fixed that in 88ade20a42515353336111385f1b33b9d177e04b
